### ISSUE TITLE
相同程序运行多次得到不同结果

### ISSUE THREAD

**Issue by DiaosWang** [yangjian1218/seetaface6ToPy#16]
我运行了作者提供的`seeta_test.py` 多次，每次得到的结果都不同，有着较小的误差。 
![image](https://github.com/yangjian1218/seetaface6ToPy/assets/47164366/b9a31d19-b003-4f95-99c4-779834d6810b)
![image](https://github.com/yangjian1218/seetaface6ToPy/assets/47164366/75af296a-9ab9-4966-9ac4-42a002a938d3)

**Comment by DiaosWang** [comment]
@yangjian1218  hello , 跪求大佬解答。

**Comment by IceHowe** [comment]
你好，我这边运行seeta_test.py报错：
root@dsw-443566-b7fff844b-5ltjq:/mnt/workspace/seetaface6ToPy# python seeta_test.py 
Traceback (most recent call last):
  File "/mnt/workspace/seetaface6ToPy/seeta_test.py", line 19, in <module>
    from seetaface.faceapi import *
  File "/mnt/workspace/seetaface6ToPy/seetaface/faceapi.py", line 44, in <module>
    dll = CDLL(os.path.join(LIB_PATH, "libSeetaFaceAPI.so"))
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libSeetaAuthorize.so: cannot open shared object file: No such file or directory

请问这个怎么解决？
